modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedDynamics/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integrateddynamics"
version="${file.jarVersion}"
displayName="IntegratedDynamics"
description='''
Take full and automated control of your appliances.
'''
[[dependencies.integrateddynamics]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.11.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrateddynamics]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.5.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrateddynamics]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrateddynamics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,]"
    ordering="NONE"
    side="BOTH"
