modLoader="javafml"
loaderVersion="[31.1,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedDynamics/issues"
[[mods]]
modId="integrateddynamics"
version="${file.jarVersion}"
displayName="IntegratedDynamics"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
description='''
Take full and automated control of your appliances.
'''
[[dependencies.integrateddynamics]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.7.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrateddynamics]]
    modId="forge"
    mandatory=true
    versionRange="[31.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrateddynamics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
